# -*- coding: utf-8 -*-
"""Loop.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rXKJC0V2yCI7Tb5a-MuYvtztYHkq-C9c
"""

x = 7
while x > 0:
  print("number {}".format(x))
  x -=1